# Generated by Django 5.1.6 on 2025-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flk_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('call_attempt', 'Call Attempt'), ('sale', 'Sale'), ('no_sale', 'No Sale')], default='new', max_length=20)),
                ('tenant', models.JSONField()),
                ('address', models.JSONField()),
                ('referring_agent', models.JSONField()),
                ('referring_agency', models.JSONField()),
                ('services', models.JSONField()),
                ('submitted', models.DateTimeField()),
                ('lease_start_date', models.DateField()),
                ('renewal', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
