# Generated by Django 5.1.6 on 2025-03-14 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_flk_lead_remove_sale_lead_delete_lead_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_first_name', models.CharField(max_length=100)),
                ('tenant_second_name', models.CharField(max_length=100)),
                ('tenant_email', models.EmailField(max_length=254, unique=True)),
                ('tenant_mobile', models.CharField(max_length=20)),
                ('address_text', models.TextField()),
                ('address_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street_number', models.CharField(max_length=10)),
                ('address_street_name', models.CharField(max_length=255)),
                ('address_locality', models.CharField(max_length=100)),
                ('address_post_code', models.IntegerField()),
                ('address_state', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_partner_code', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_email', models.EmailField(max_length=254)),
                ('agency_partner_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gas', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('pay_tv', models.BooleanField(default=False)),
                ('cleaning', models.BooleanField(default=False)),
                ('removalist', models.BooleanField(default=False)),
                ('moving_boxes', models.BooleanField(default=False)),
                ('vehicle_hire', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_start_date', models.DateField()),
                ('renewal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
