# Generated by Django 5.1.6 on 2025-03-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
