# Generated by Django 5.1.6 on 2025-03-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_delete_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flk_lead',
            name='lease_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
