# Generated by Django 5.1.6 on 2025-03-21 10:08

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_flk_lead_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flk_lead',
            name='extra',
            field=models.JSONField(default=crm.models.default_extra),
        ),
    ]
