# Generated by Django 5.1.7 on 2025-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(blank=True, max_length=50)),
                ('products', models.JSONField(default=list)),
                ('customer_type', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('best_contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('is_billing_same_as_physical', models.BooleanField(blank=True, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('how_did_you_hear', models.CharField(blank=True, max_length=100)),
                ('is_owner', models.BooleanField(blank=True, null=True)),
                ('has_solar', models.BooleanField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=20)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_expiry', models.CharField(blank=True, max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=50)),
                ('mobile_phone', models.CharField(blank=True, max_length=50)),
                ('confirm_email', models.EmailField(blank=True, max_length=254)),
                ('wants_secondary_contact', models.BooleanField(blank=True, null=True)),
                ('secondary_title', models.CharField(blank=True, max_length=20)),
                ('secondary_first_name', models.CharField(blank=True, max_length=100)),
                ('secondary_last_name', models.CharField(blank=True, max_length=100)),
                ('secondary_mobile', models.CharField(blank=True, max_length=50)),
                ('secondary_home_phone', models.CharField(blank=True, max_length=50)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('move_in_date', models.DateTimeField(blank=True, null=True)),
                ('has_been_disconnected12months', models.BooleanField(blank=True, null=True)),
                ('has_building_electrical_works', models.BooleanField(blank=True, null=True)),
                ('has_clear_meter_access', models.BooleanField(blank=True, null=True)),
                ('life_support', models.BooleanField(blank=True, null=True)),
                ('is_concession_holder', models.BooleanField(blank=True, null=True)),
                ('concession_type', models.CharField(blank=True, max_length=100)),
                ('concession_card_number', models.CharField(blank=True, max_length=50)),
                ('concession_card_start_date', models.CharField(blank=True, max_length=20)),
                ('concession_card_expiry_date', models.CharField(blank=True, max_length=20)),
                ('medical_cooling_concession', models.BooleanField(blank=True, null=True)),
                ('concessioner_declaration_provided', models.BooleanField(blank=True, null=True)),
                ('consent_electronic_bills', models.BooleanField(blank=True, null=True)),
                ('all_communication_same_method', models.BooleanField(blank=True, null=True)),
                ('use_primary_email_for_all', models.BooleanField(blank=True, null=True)),
                ('is_postal_address_correct', models.BooleanField(blank=True, null=True)),
                ('monthly_bills_ok', models.BooleanField(blank=True, null=True)),
                ('promotional_contact_consent', models.BooleanField(blank=True, null=True)),
                ('has_reviewed_market_offer_summary', models.BooleanField(blank=True, null=True)),
                ('has_reviewed_eic_script', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
